In [1]:
import numpy as np
a=np.array([2,7,1,99,4])
type(a)


numpy.ndarray

In [2]:
import numpy as np
b=np.array([12,17 ,11,199,14])
type(b)

numpy.ndarray

In [3]:
type(a)

numpy.ndarray

In [4]:
a[0]

2

In [5]:
b[0]

12

In [6]:
a+b

array([ 14,  24,  12, 298,  18])

In [7]:
a

array([ 2,  7,  1, 99,  4])

In [0]:
c=a+b

In [9]:


c

array([ 14,  24,  12, 298,  18])

In [0]:
m=a*b

In [11]:
m

array([   24,   119,    11, 19701,    56])

In [0]:
a5=a+5

In [13]:
a5

array([  7,  12,   6, 104,   9])

In [0]:
x=np.array([[2,5,8],[3,6,1]])

In [15]:
x

array([[2, 5, 8],
       [3, 6, 1]])

In [16]:
x[0]

array([2, 5, 8])

In [17]:
x[0][1]

5

In [18]:
x+7

array([[ 9, 12, 15],
       [10, 13,  8]])

In [0]:
y=x+7

In [20]:
x*2

array([[ 4, 10, 16],
       [ 6, 12,  2]])

In [0]:
z=np.array([[2,7],[3,8],[2,9],[9,4]])

In [22]:
z

array([[2, 7],
       [3, 8],
       [2, 9],
       [9, 4]])

In [23]:
x

array([[2, 5, 8],
       [3, 6, 1]])

In [24]:


x.shape

(2, 3)